import Head from "next/head";
import LandingPage from "@/components/LandinPage/LandingPage";
import Header from "@/components/Header";
import HomePage from "@/components/home";
import { useGlobalState } from "@/context/global.context";
import AuthModal from "@/components/AuthModal/AuthModal";

export default function Home() {
  const { showAuthModal, setShowAuthModal } = useGlobalState();
  return (
    <>
      {showAuthModal && (
        <AuthModal
          handleClose={() => {
            setShowAuthModal(false);
          }}
        />
      )}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LandingPage /> */}
      <HomePage />
    </>
  );
}
