import Head from "next/head";
import LandingPage from "@/components/LandinPage/LandingPage";
import Header from "@/components/Header";
import HomePage from "@/components/home";
import { useGlobalState } from "@/context/global.context";
import AuthModal from "@/components/AuthModal/AuthModal";
import { AUTH_TOKEN } from "@/util/constants";
import { useEffect, useState } from "react";

export default function Home() {
  const { showAuthModal, setShowAuthModal } = useGlobalState();
  const [tokenPresent, setTokenPresent] = useState<any>(false);

  useEffect(() => {
    setTokenPresent(localStorage.getItem(AUTH_TOKEN));
  }, []);
  return (
    <>
      {showAuthModal && (
        <AuthModal
          handleClose={() => {
            setShowAuthModal(false);
          }}
        />
      )}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!tokenPresent ? <LandingPage /> : <HomePage />}
    </>
  );
}
